# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TenMinDemo' do
    # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    #  use_frameworks!
    
    # Pods for CYXText
    pod 'AFNetworking', '~> 3.0'
    pod "SDWebImage"
    pod "MJExtension"
    pod "MJRefresh"
    pod 'SVProgressHUD'
    pod 'ReactiveObjC'
    
end

target 'TenMinDemoTests' do
    use_frameworks!
    pod 'KIF', '~> 3.5.1'
end
